### ISSUE TITLE
too many values to unpack

### ISSUE THREAD

**Issue by kennethgillen** [ome/ansible-role-network#4]
The inclusion of https://github.com/openmicroscopy/ansible-role-network/pull/3 has broken the current state of prod-playbooks and management_tools inventory.

It was working and tested with the previous version of this role (as was used to most recently deploy `ome-web-rw`).

Now this PR is merged, prod-playbooks is broken with 

```
"msg": "ValueError: too many values to unpack"}
```

```
ome-k8s-pg-01.openmicroscopy.org : ok=1    changed=0    unreachable=0    failed=1
ome-lochy-m01.openmicroscopy.org : ok=1    changed=0    unreachable=0    failed=1
ome-lochy-n01.openmicroscopy.org : ok=1    changed=0    unreachable=0    failed=1
ome-lochy-n02.openmicroscopy.org : ok=1    changed=0    unreachable=0    failed=1
ome-web-rw.openmicroscopy.org : ok=1    changed=0    unreachable=0    failed=1
```

I presume this is something to do with how the list / dictionary / etc is structured in https://github.com/openmicroscopy/management_tools/blob/master/ansible/inventory/group_vars/vlan-10ge-servers ?

i.e. if you've removed `.items()` then do we need to change the data structure in the group_vars file?

**Comment by manics** [comment]
What's the full error message, tasks and hosts leading up to `"msg": "ValueError: too many values to unpack"}`?

**Comment by joshmoore** [comment]
Discussed with @kennethgillen . He's going to re-run against pub-omero to get this log.

**Comment by kennethgillen** [comment]
https://github.com/openmicroscopy/ansible-role-network/pull/5 fixed this. Thanks @manics.
